### ISSUE TITLE
Error 400 on pusing gem on local server

### ISSUE THREAD

**Issue by kasargee** [geminabox/geminabox#105]
I have installed geminabox latest version and ran the config.ru file and started the server.
server is running on http://localhost:9292. When i am hitting http://localhost:9292 in IE, it is updating on command prompt where server is running with 200 code.

But when i try to use command-
C:\MyGems\rica-master>gem inabox ./rica-0.0.1.gem
Pushing rica-0.0.1.gem to http://localhost:9292/...
ERROR:  Error (400 received)

I am using "USe automatic configuration script" and HTTP_PROXY variable is set to company provided address.
Please help me with solution.

**Comment by BenNG** [comment]
I also have the problem on linux debian jessie
```
Pushing Gemfile to http://0.0.0.0:3000/...
400Cannot process gem
```

**Comment by ctdocken** [comment]
Create a folder in the root directory of whatever drive is running geminabox called "tmp." If you're running Windows, it's "C:\tmp". Most *nix machines won't have this issue since the tmp directory is created when the operating system is installed.
