### ISSUE TITLE
Race condition in incremental indexing

### ISSUE THREAD

**Issue by jfoy** [geminabox/geminabox#115]
Given a geminabox 0.8.3 instance with `:incremental_updates` enabled
And a data directory `/var/geminabox-data`
When User A triggers a `reindex(:force_rebuild)`, such as by deleting a gem
And during the reindex User B uploads a gem, triggering an incremental reindex
Then the result of the full reindex will be stored in `/var/geminabox-data/quick/Marshal.4.8/Marshal.4.8/*.rz` , one directory too deep
And the directory `/var/geminabox-data/quick/Marshal.4.8/*.rz` will contain only the file resulting from the incremental index
And bundler will return an API error

We fixed this by running `mv Marshal.4.8/Marshal.4.8/*.rz Marshal.4.8/.`

**Comment by brendon9x** [comment]
This just happened to me so it is still a problem.  It happened because deleting a gem is quite slow so I clicked it a second time.
