### ISSUE TITLE
Error during API request. Bundler::HTTPError: Net::HTTPInternalServerError

### ISSUE THREAD

**Issue by danielfoglio** [geminabox/geminabox#160]
Fetching from: http://#{ROOT_URL_HERE}/api/v1/dependencies?gems=rake,diff-lcs,facter,json_pure,hiera,highline,json,thor,librarian-puppet,metaclass,mocha,net-ssh,rgen,puppet,puppet-lint,rspec-core,rspec-expectations,rspec-mocks,rspec,rspec-puppet,puppetlabs_spec_helper,serverspec
Error during API request. Bundler::HTTPError: Net::HTTPInternalServerError: <!DOCTYPE html>
 <html>
   <head>
   <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<title>Errno::ECONNRESET at &#x2F;rubygems&#x2F;api&#x2F;v1&#x2F;dependencies</title>
..........
 <td>sinatra.error</td>
        <td class="code"><div>#&lt;Errno::ECONNRESET: Connection reset by peer - SSL_connect&gt;</div></td>
       </tr>
.......
/export/home/code_builds/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.3.5/lib/bundler/fetcher.rb:229:in `fetch'  /export/home/code_builds/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.3.5/lib/bundler/fetcher.rb:222:in`fetch'  /export/home/code_builds/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.3.5/lib/bundler/fetcher.rb:242:in `fetch_dependency_remote_specs'  /export/home/code_builds/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.3.5/lib/bundler/fetcher.rb:151:in`fetch_remote_specs'  /export/home/code_builds/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.3.5/lib/bundler/fetcher.rb:106:in `specs'  /export/home/code_builds/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.3.5/lib/bundler/source/rubygems.rb:235:in`block in remote_specs'  /export/home/code_builds/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.3.5/lib/bundler/source/rubygems.rb:235:in `each'  /export/home/code_builds/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.3.5/lib/bundler/source/rubygems.rb:235:in`remote_specs'  /export/home/code_builds/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.3.5/lib/bundler/source/rubygems.rb:163:in `fetch_specs'  /export/home/code_builds/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.3.5/lib/bundler/source/rubygems.rb:67:in`specs'  /export/home/code_builds/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.3.5/lib/bundler/lazy_specification.rb:52:in `__materialize__'  /export/home/code_builds/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.3.5/lib/bundler/spec_set.rb:88:in`block in materialize'  /export/home/code_builds/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.3.5/lib/bundler/spec_set.rb:85:in `map!'  /export/home/code_builds/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.3.5/lib/bundler/spec_set.rb:85:in`materialize'  /export/home/code_builds/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.3.5/lib/bundler/definition.rb:114:in `specs'  /export/home/code_builds/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.3.5/lib/bundler/definition.rb:109:in`resolve_remotely!'  /export/home/code_builds/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.3.5/lib/bundler/installer.rb:83:in `run'  /export/home/code_builds/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.3.5/lib/bundler/installer.rb:14:in`install'  /export/home/code_builds/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.3.5/lib/bundler/cli.rb:247:in `install'  /export/home/code_builds/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.3.5/lib/bundler/vendor/thor/task.rb:27:in`run'  /export/home/code_builds/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.3.5/lib/bundler/vendor/thor/invocation.rb:120:in `invoke_task'  /export/home/code_builds/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.3.5/lib/bundler/vendor/thor.rb:344:in`dispatch'  /export/home/code_builds/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.3.5/lib/bundler/vendor/thor/base.rb:434:in `start'  /export/home/code_builds/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.3.5/bin/bundle:20:in`block in <top (required)>'  /export/home/code_builds/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.3.5/lib/bundler/friendly_errors.rb:3:in `with_friendly_errors'  /export/home/code_builds/.rvm/gems/ruby-2.0.0-p353/gems/bundler-1.3.5/bin/bundle:20:in`<top (required)>'  /export/home/code_builds/.rvm/gems/ruby-2.0.0-p353/bin/bundle:23:in `load'  /export/home/code_builds/.rvm/gems/ruby-2.0.0-p353/bin/bundle:23:in`<main>'  /export/home/code_builds/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in `eval'  /export/home/code_builds/.rvm/gems/ruby-2.0.0-p353/bin/ruby_executable_hooks:15:in`<main>'
     [exec] Fetching source index from http://code/rubygems/

It then downloads everything in /quick/Marshal.4.8

This error does not happen all the time, however it does happen..

**Comment by newdark** [comment]
It is because of bad data in your Marshal folder. the path should be this

```ruby
Geminabox.data + '/proxy/quick/Marshal.4.8/
```

The root path is where ever your data is stored for the gems. Just by clearing out that folder/directory you should see the error go away. However it will make everything super slow until it can rebuild all the rz files. 

There are other ways to find the file the broken file but I found this to be the fastest way to resolve the problem
