### ISSUE TITLE
Indexer with ruby >=2

### ISSUE THREAD

**Issue by nevesenin** [geminabox/geminabox#170]
Hi,

I found another funny thing, which I think should be fixed. If geminabox is running under ruby >= 2 it does not index the default gems. So it is not possible to install json-1.8.1 from geminabox for example if geminabox is running with ruby 2.1.0.

Merten

**Comment by juniorz** [comment]
I faced this issue today. It actually happens that `gem generate_index` also fails to reindex `json-1.8.1` - it simply skips the gem. So I don't think this is a `geminabox` issue, but rather a `rubygems` issue.

I updated gem to the latest version (with a `gem update --system`) with no success.

**Comment by obxhdx** [comment]
@nevesenin I believe [this issue](https://github.com/rubygems/rubygems/issues/661) on rubygems repo is the reason behind this behaviour.

**Comment by katafrakt** [comment]
I just checked with master rubygems and my json-1.8.1 was indexed just fine, however latest stable version still has this bug.
