### ISSUE TITLE
HTTPS not used when proxying to rubygems.org

### ISSUE THREAD

**Issue by lmarlow** [geminabox/geminabox#183]
Both locations that proxy through to rubygems.org do not use SSL. Is there a reason these aren't `https` URLs by default?

[`Geminabox::Proxy::FileHandler#remote_url`](https://github.com/geminabox/geminabox/blob/9ddd36c18cbe7d883c9f6131faa1cbf8d439b68f/lib/geminabox/proxy/file_handler.rb#L52)
[`Geminabox::Proxy::Hostess#get_from_rubygems_if_not_local`](https://github.com/geminabox/geminabox/blob/9ddd36c18cbe7d883c9f6131faa1cbf8d439b68f/lib/geminabox/proxy/hostess.rb#L62)

**Comment by Primer42** [comment]
bump.  `geminabox` should definitely use https when talking to rubygems.org

**Comment by lmarlow** [comment]
This still points to non-HTTPS: https://github.com/geminabox/geminabox/blob/master/lib/geminabox/proxy/file_handler.rb#L52
