### ISSUE TITLE
Support for gem stores other than local filesystem

### ISSUE THREAD

**Issue by bkon** [geminabox/geminabox#187]
Background:
- we're running geminabox in AWS environment as a part of auto-scaling group;
- we'd like to be able to push our own gems.

Problem:
- when gem is pushed, it gets stored on one instance only, so attempts to fetch this gem may fail intermittently depending on which instance request is routed to;
- if this instance is replaced, previously published gem is lost.

Suggested solution is to update hostess / gem store classes to allow for some kind of persistent gem store which could be shared between instances.

Pull request is on the way.

**Comment by b-dean** [comment]
@bkon, I've been looking at [bkon/geminabox-s3-store](https://github.com/bkon/geminabox-s3-store) and in its README it mentions setting 

```ruby
Geminabox.store = Geminbox::S3::Store.new bucket: some_bucket
```

You also mention an upcoming PR but that never happened. I assume that would be from [VodafoneAustralia/geminabox@feature/store-abstraction](https://github.com/VodafoneAustralia/geminabox/tree/feature/store-abstraction). 

Is there any chance this will be done? Or is it abandonded?

**Comment by bkon** [comment]
It's kind of abandoned, as I've moved to a position in a different company and we don't use geminabox in our current environment; doing a proper PR with proper tests is rather resource-consuming task, sorry.
