### ISSUE TITLE
Feature request: proxying sources other than rubygems.org.

### ISSUE THREAD

**Issue by bkon** [geminabox/geminabox#189]
Background: there are other public gem sources (http://rails-assets.org to name one) we'd like to cache / proxy gems from. 

Problem:
- at the moment reference to 'rubygems.org' is hardcoded in ```Geminabox::Proxy::FileHandler``` class;
- there's no mechanism to support for more than one gem source.

Suggested solution: generalise proxy code to support a list of proxies.

**Comment by natebird** [comment]
Pull request [205](https://github.com/geminabox/geminabox/pull/205) addresses this issue. Test it and up vote to bring some attention to the feature.
