### ISSUE TITLE
Cant start geminabox  - puma error

### ISSUE THREAD

**Issue by machzqcq** [geminabox/geminabox#190]
I saw another issue that had issues loading "LibYaml" and tried all options suggested on that issue after which version 0.12.4 was released. I have Ruby 2.0.0p594 and geminabox 0.12.4.
Might have tried 100 different ways and searched at least 2 pages deep into google search, but couldn't figure out the issue. So did rackup -d and below is the error.
Any suggestions please? I had Geminabox working on another windows box without any errors and I have not done anything different on this windows box, both had windows 7 same version and pretty much same environmental settings

config.ru
------------
require "rubygems"
require "geminabox"

Geminabox.data = "c:/data"
Geminabox.rubygems_proxy = true
run Geminabox::Server

---------------------------------------------------

C:\seleniumframework\geminabox-repo>rackup -d
nil
Exception `LoadError' at C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54 - cannot load such file -- geminabox
Exception `LoadError' at C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54 - cannot load such file -- xml/parser
Exception `LoadError' at C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:133 - cannot load such file -- xml/parser
Exception `LoadError' at C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54 - cannot load such file -- xmlparser
Exception `LoadError' at C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:133 - cannot load such file -- xmlparser
Exception `LoadError' at C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:133 - cannot load such file -- xmlparser
Exception `LoadError' at C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54 - cannot load such file -- xmlscan/scanner
Exception `LoadError' at C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:133 - cannot load such file -- xmlscan/scanner
Exception `LoadError' at C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:133 - cannot load such file -- xmlscan/scanner
Using Ext extension for JSON.
Exception `LoadError' at C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54 - cannot load such file -- addressable/uri
Exception `LoadError' at C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54 - cannot load such file -- idn
Exception `LoadError' at C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:133 - cannot load such file -- idn
Exception `LoadError' at C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:133 - cannot load such file -- idn
Exception `LoadError' at C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54 - cannot load such file -- thin
Exception `LoadError' at C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:133 - cannot load such file -- thin
Exception `LoadError' at C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:54 - cannot load such file -- rack/handler/puma
Exception `LoadError' at C:/Ruby200/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:133 - cannot load such file -- rack/handler/puma
Exception `NameError' at C:/Ruby200/lib/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/handler.rb:22 - wrong constant name puma
Exception `LoadError' at C:/Ruby200/lib/ruby/gems/2.0.0/gems/rack-1.5.2/lib/rack/handler.rb:26 - cannot load such file -- rack/handler/puma
#<Rack::ContentLength:0x44c0910
 @app=
  #<Rack::Chunked:0x44c0940
   @app=
    #<Rack::CommonLogger:0x44c0970
     @app=
      #<Rack::ShowExceptions:0x3927660
       @app=
        #<Rack::Lint:0x3927690 @app=Geminabox::Server, @content_length=nil>,
       @template=
        #<ERB:0x3927648
         @enc=#<Encoding:UTF-8>,
         @filename=nil,
         @safe_level=nil,
         @src=
          "#coding:UTF-8\n_erbout = ''; _erbout.concat \"<!DOCTYPE HTML PUBLIC \\\"-//W3C//DTD 

.............................and lots more content, I just removed it as it was getting formatted

**Comment by natebird** [comment]
It looks like it can’t find the gems you installed. Are there multiple versions of Ruby installed on the machine?
