### ISSUE TITLE
Seperate local Gems from proxy (cached) Gems

### ISSUE THREAD

**Issue by paulclarkin** [geminabox/geminabox#193]
It would be nice if it was possible to store the Gems which have been downloaded from rubygems in a separate folder to the ones which have been manually uploaded to geminabox.

In addition, it would be nice if it was possible to flush the proxy cache from time to time, without touching the Gems that have been manually uploaded.

**Comment by olbat** [comment]
+1

**Comment by natebird** [comment]
:+1:

**Comment by Lambenttelos** [comment]
Very much agree. In a larger corporate deployment we have 20+ separate ruby projects all pulling their gems through one server and it can get pretty cluttered.

**Comment by tmaier** [comment]
Hi, I suggest you to set up two separate Geminabox instances. One as the proxy only, the second one for your private gems. See the reasoning behind this at #208
