### ISSUE TITLE
Gem in the server but cannot retrieve

### ISSUE THREAD

**Issue by dennispark91** [geminabox/geminabox#196]
Hello,

I've created gembox on a linux vm and am using nginx to reverse proxy the port.
(example: http://gemserver.com sent to http://gemserver.com:9292)

The problem I am having is, when I upload gems to http://gemserver.com, it sometimes doesn't show up on the gembox and cannot be retrieved via geminabox command. Yet when I check the gem directory in the server, the gems are all there. Maybe this has something to do with reverse proxying because the old gembox which doesn't use reverse proxy updates very well.

Is there any way for me to make sure that the gems are correctly displayed and retrieved when they are in the server? (I have tried reindex)

**Comment by tmaier** [comment]
do you still have the issue? #215 could give you a hint on the correct nginx configuration.
