### ISSUE TITLE
Support more than one proxy location

### ISSUE THREAD

**Issue by stewartmatheson** [geminabox/geminabox#198]
I would like it if GIAB pulled from rails-assets as well as rubygems.org. I am happy to submit a patch for this if the authors feel its worthwhile.  My idea would be to change the following

1. Add a sources class that would contain the correct urls for each source. 

2. Rename the RubygemsDependency to ExternalDependency

3. Refactor this new ExternalDependencey to iterate over the sources class and hit each proxy

4. Refactor Geminabox::Proxy::FileHeander#remote_content to look at all sources untill it finds the gem. I am gussing we just fail over to the next source if we get a not found.

At this point I am not sure if it's worth caching the origins of gems during the dependency.json call but if we wrote that to the data folder somewhere then we know exactly what source to hit. 

Thoughts? What issues have I overlooked?

**Comment by 1st8** [comment]
This would be very useful to me, too.

**Comment by dserodio** [comment]
:+1:

**Comment by stewartmatheson** [comment]
Pull request created for this. Please test if you have a chance. 

https://github.com/geminabox/geminabox/pull/205

**Comment by javierav** [comment]
:+1:  for proxy rails-assets

**Comment by stewartmatheson** [comment]
Hey @javierav check the pull request. I this is now working with configurable proxy locations.
