### ISSUE TITLE
Dockerize your project

### ISSUE THREAD

**Issue by BenNG** [geminabox/geminabox#199]
https://github.com/geminabox/geminabox/wiki/Use-with-Docker is not working anymore. I was wondering if you could provide a Dockerfile at the root of the project in order to run it ? Cheers

**Comment by j-a-m-l** [comment]
I have just created https://github.com/j-a-m-l/jewellery.rb for this kind of thing. I guess that it could be used as a sample of how to achieve the "dockerization".

Any thoughts about it?

BTW: awesome project!

**Comment by odigity** [comment]
+1 for Dockerfile; would also be convenient if ya'll could create an image and upload it to Docker Hub under the geminabox/ namespace so people will be more likely to trust it.

I might upload my own in the meantime, but there's no substitute for proper branding.  :)

(Hope this gets released soon so I don't have to point at master...)

**Comment by strarsis** [comment]
https://github.com/strarsis/docker-geminabox

With best regards
