### ISSUE TITLE
Rubygems proxy race condition

### ISSUE THREAD

**Issue by Primer42** [geminabox/geminabox#202]
Hello,

We're using geminabox with unicorn, behind an nginx reverse proxy.  We have the rubygems proxy configuration enabled.

We noticed that intermittently, calling `gem list --remote --clear-sources --source <our geminabox server> <gem name>` would hang, and never complete.

We saw the following log messages in the nginx error log:
```
2015/05/08 13:05:20 [error] 16851#0: *70457234 upstream prematurely closed connection while reading upstream, client: <ip address>, server: <geminabox server>, request: "GET /latest_specs.4.8.gz HTTP/1.1", upstream: "https://127.0.0.1:7707/latest_specs.4.8.gz", host: "<geminabox server>"
```
And the following in the unicorn error logs:
```
E, [2015-05-08T13:05:20.418185 #340] ERROR -- : app error: Content-Length header was 871233, but should be 458752 (Rack::Lint::LintError)
E, [2015-05-08T13:05:20.418275 #340] ERROR -- : /opt/ruby/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/lint.rb:20:in `assert'
E, [2015-05-08T13:05:20.418302 #340] ERROR -- : /opt/ruby/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/lint.rb:631:in `verify_content_length'
E, [2015-05-08T13:05:20.418326 #340] ERROR -- : /opt/ruby/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/lint.rb:655:in `each'
E, [2015-05-08T13:05:20.418349 #340] ERROR -- : /opt/ruby/2.2.0/lib/ruby/gems/2.2.0/gems/rack-1.5.2/lib/rack/body_proxy.rb:31:in `each'
E, [2015-05-08T13:05:20.418372 #340] ERROR -- : /opt/ruby/2.2.0/lib/ruby/gems/2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_response.rb:60:in `http_response_write'
E, [2015-05-08T13:05:20.418395 #340] ERROR -- : /opt/ruby/2.2.0/lib/ruby/gems/2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:586:in `process_client'
E, [2015-05-08T13:05:20.418417 #340] ERROR -- : /opt/ruby/2.2.0/lib/ruby/gems/2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:670:in `worker_loop'
E, [2015-05-08T13:05:20.418440 #340] ERROR -- : /opt/ruby/2.2.0/lib/ruby/gems/2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:525:in `spawn_missing_workers'
E, [2015-05-08T13:05:20.418462 #340] ERROR -- : /opt/ruby/2.2.0/lib/ruby/gems/2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:536:in `maintain_worker_count'
E, [2015-05-08T13:05:20.418489 #340] ERROR -- : /opt/ruby/2.2.0/lib/ruby/gems/2.2.0/gems/unicorn-4.8.3/lib/unicorn/http_server.rb:294:in `join'
E, [2015-05-08T13:05:20.418512 #340] ERROR -- : /opt/ruby/2.2.0/lib/ruby/gems/2.2.0/gems/unicorn-4.8.3/bin/unicorn:126:in `<top (required)>'
E, [2015-05-08T13:05:20.418535 #340] ERROR -- : /opt/ruby/2.2.0/bin/unicorn:23:in `load'
E, [2015-05-08T13:05:20.418557 #340] ERROR -- : /opt/ruby/2.2.0/bin/unicorn:23:in `<main>'
```

I did a `watch -n .1 ls -la /<geminabox data directory>/proxy` and noticed that the size of the `latest_specs.4.8.gz` file is switching between 0 and its correct size of ~870 KB every second or two, sometimes multiple times a second.  Less frequently, I saw the same thing happen to the `specs.4.8.gz` file.

My theory is that there is a race condition between the unicorn workers, where one worker must be trying to download a new copy of the `lastest_specs.4.8.gz` from rubygems, and before it completes another worker serves the partial file.

I have looked at the proxy code, but have not been able to determine why geminabox is trying to update the file so frequently.

Can anyone else reproduce this?

Thanks!

**Comment by Primer42** [comment]
This is a pretty major problem for us, so any attention or advice on how to address it would be really helpful.

**Comment by byxorna** [comment]
Could just be solved by downloading the specs.gz to a temporary file and performing an atomic mv to the target path. I havent looked to see where that should be happening though.

**Comment by JohnMorales** [comment]
@Primer42, were you able to get to the bottom of this? I'm seeing the same error as well.

**Comment by Primer42** [comment]
@JohnMorales - we have the theory we outlined about what is going wrong, but we haven't had a chance to try to patch it.  We've ended up just adding timeout and retry logic to our gem installation automation.  It isn't a great solution, and I would much prefer if the race condition didn't exist in the first place.
