### ISSUE TITLE
Domain Name in source results in Bundler::MarshalError ArgumentError: dump format error for symbol(0x72)

### ISSUE THREAD

**Issue by fsauter** [geminabox/geminabox#206]
Hi, I have a strange error:

When I have the following in my Gemfile:

``` ruby
source "http://user:#{ENV['GEM_SERVER_KEY']}@geminabox.fsauter.de"
```

I receive (during bundle install):

``` console
Fetching gem metadata from http://geminabox.fsauter.de/.Retrying dependency api due to error (2/4): Bundler::MarshalError ArgumentError: dump format error for symbol(0x72)
Retrying dependency api due to error (3/4): Bundler::MarshalError ArgumentError: dump format error for symbol(0x72)
Retrying dependency api due to error (4/4): Bundler::MarshalError ArgumentError: dump format error for symbol(0x72)
```

If I use the IP adress instead of the domain name, everything works fine:

``` ruby
source "http://user:#{ENV['GEM_SERVER_KEY']}@78.47.50.93"
```

I use apache2 together with the latest passenger module and ruby 2.1.5.

Locally the gems are downloaded anyway but my build server seems to abort the build due to this error.

Any hints on this?

**Comment by colstrom** [comment]
+1, experiencing the issue.

**Comment by sonots** [comment]
Bundler::MarshalError is possibly occurred at only `Bundler#load_marshal` https://github.com/bundler/bundler/blob/e6cc7a24d5ca9da842aeefd23167be4d850c9aa5/lib/bundler.rb#L430

load_marshal is a method to load `Marshal.dump`ed data, so I guess this issue is not related with URL.

```
lib/bundler/fetcher/dependency.rb
58:          gem_list.concat(Bundler.load_marshal(marshalled_deps))

lib/bundler/fetcher/index.rb
32:          Bundler.load_marshal Gem.inflate(Gem.read_binary(uri.path))
36:          Bundler.load_marshal Gem.inflate(downloader.fetch(uri).body)

lib/bundler/fetcher.rb
99:        Bundler.load_marshal Gem.inflate(Gem.read_binary(uri.path))
103:        Bundler.load_marshal Gem.inflate(downloader.fetch(uri).body)
```

I tried to reproduce, but I could not do it.
Do you get the error with your config 100% possibility?

**Comment by sonots** [comment]
Please reopen if you still encounter with this problem.
