### ISSUE TITLE
CLI Authentication problem with Rack::Auth::Basic

### ISSUE THREAD

**Issue by sronsiek** [geminabox/geminabox#209]
The wiki at  https://github.com/geminabox/geminabox/wiki/Http-Basic-Auth  documents this authentication code:

    Rack::Auth::Basic, "GemInAbox" do |username, password|
      'your massively secure password' == password
    end

I have exactly this code running - and indeed it works nicely when the client is a browser. But from the command line the following does call not work:

    gem push some.gem --host http://<user>:<passwd>@hostname.doman

There is no error output, and on the server the WEBrick output is:

    172.17.42.1 - - [12/Aug/2015:16:56:18 +0000] "POST /api/v1/gems HTTP/1.1" 401 - 0.0005

but nothing is ingested. Note when using a browser, the second dash in the log displays the user name.

Is there a way of getting this authentication to work?

NOTE: I'm already using the '.gem/credentials' workaround described here:

https://github.com/jgraichen/geminabox-rake/issues/3

**Comment by cwninja** [comment]
I'm not sure the `gem push` command is supposed to be supported.

Does it work with the `gem inabox` command?

**Comment by DmitrySharikov** [comment]
for me this works fine

```shell
gem inabox hermes-0.1.0.gem --host http://username:password@localhost:9292
```
