### ISSUE TITLE
0.12.4 not working with ruby 1.8.7 

### ISSUE THREAD

**Issue by ronald** [geminabox/geminabox#214]
gem inabox $file --host $host

/usr/lib/ruby/vendor_ruby/1.8/rubygems/custom_require.rb:55:in `gem_original_require': /usr/local/rbenv/versions/1.8.7-debian/gems/gems/geminabox-0.12.4/lib/geminabox.rb:66: syntax error, unexpected ':', expecting ')' (SyntaxError)
    data:                 File.join(Fil...

I'd suggest to support 1.8.7 or add spec.required_ruby_version' to .gemspec.

**Comment by tmaier** [comment]
This error message is related to the "new" hash syntax introduces with Ruby 1.9

Ruby 1.8.7 reached its end of life some time ago.  See https://www.ruby-lang.org/en/news/2013/06/30/we-retire-1-8-7/

Btw. Ruby 1.9 has also reached its end of life.

required_ruby_version is an optional parameter. See http://guides.rubygems.org/specification-reference/#required_ruby_version

If you think required_ruby_version is required, please provide a pull request.

Thanks

**Comment by cwninja** [comment]
I'm going to go ahead and agree with @tmaier, latest master now only being tested against 2.1.8, 2.2.4, 2.3.0.
