### ISSUE TITLE
where to configure the host?

### ISSUE THREAD

**Issue by andywenk** [geminabox/geminabox#215]
Hi all,

sorry for asking maybe a trivial question. We have installed geminabox on one of our servers and start it with:

*nginx*

       location / {
          [...]
          proxy_pass  http://127.0.0.1:9292/;
          proxy_redirect http://127.0.0.1:9292/ http://gems.ourhost.net/;
       }

*init.d script*

       do_start()
       {
            su - www-data -c "cd $PFAD; rackup --pid $PID -D -s thin >> $LOG 2>&1;"
       }

This will make the rack application available at  http://gems.ourhost.net/ but the links (e.g. upload) have still 127.0.0.1:9292 as the host. Where I do I change this to the IP or domain gems.ourhost.net?

I expected some configuration in geminabox but did not find it. Btw. yes we need nginx because there is also other stuff running on this machine.

Thanks a lot for your help and for geminabox.

Cheers

Andy

**Comment by tmaier** [comment]
All URLs within Geminabox are relative URLs. None of them has the host somewhere in the HTML output. In fact, the upload form does not even define any form path (see https://github.com/geminabox/geminabox/blob/master/views/upload.erb)

In the end, Geminabox is a Sinatra application. You could check out http://www.sinatrarb.com/configuration.html. Maybe there is something you could configure.

But to be honest, this sounds like a configuration problem of your nginx setup. But I am not qualified to give you any hints where to look there exactly.

**Comment by andywenk** [comment]
@tmaier thanks a lot for your reply. Yes indeed, it was a nginx config problem. Due to the fact, that we use the Sinatra app in an SSL environment, we needed to add some extra Headers:

    # a HTTP header important enough to have its own Wikipedia entry:
    #   http://en.wikipedia.org/wiki/X-Forwarded-For
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    # enable this if you forward HTTPS traffic to unicorn,
    # this helps Rack set the proper URL scheme for doing redirects:
    proxy_set_header X-Forwarded-Proto $scheme;

    # pass the Host: header from the client right along so redirects
    # can be set properly within the Rack application
    proxy_set_header Host $http_host;
      proxy_pass  http://127.0.0.1:9292/;
      proxy_redirect http://127.0.0.1:9292/ https://gems.yourserver.com/;
    }

Maybe this helps someone in the future.

**Comment by tmaier** [comment]
Great it is resolved. Thanks for sharing your solution
