### ISSUE TITLE
Render HTTPS links 

### ISSUE THREAD

**Issue by erikanderson** [geminabox/geminabox#216]
I am in the process of moving our geminabox server and configuring it to use SSL (through NGINX). Everything loads fine when in SSL but the rendered links are still http (like the links at the top showing how to add the sources). I can still download the gems so I don't think it is an NGINX config issue.

**Comment by cwninja** [comment]
Looks like the following may be of use. This issue comes when the backend app has no idea that you're using TLS because nginx is effectively stripping it when it does the downstream http request.

http://stackoverflow.com/questions/6330595/how-to-fix-sinatra-redirecting-https-to-http-under-nginx
