### ISSUE TITLE
Can't remove Gem reference from private hub website

### ISSUE THREAD

**Issue by KenReedNXP** [geminabox/geminabox#218]
On our internal hub we have a number of Gems.  We now have some that are outdated and need to be removed.  On the website, we can hit the red "delete" button for a Gem version.  We get the message that "Sinatra doesn't know this ditty", but we are pretty sure the Gem is gone because we can no longer access it.  But the reference to that Gem version is still on the website, we don't know how to delete it.  We would also like to be able to completely delete all versions of some Gems including their title in the web page.  Still very new to this so any help would be appreciated.  Below is an example, we would like to remove all of this from the website

![geminaboxexample](https://cloud.githubusercontent.com/assets/17086301/12852343/1245817a-cbf4-11e5-8365-71c83bb93295.png)

**Comment by cwninja** [comment]
Do you know what URL it has been redirected to when you see the "Sinatra doesn't know this ditty" page?

**Comment by KenReedNXP** [comment]
It looks like it is pointing to the actual Gem :
http://<NXP<http://%3cNXP> internal hub>/gems/vref1v2_gen_xxxxx_tester-1.0.0.gem

**Comment by sonots** [comment]
I could not reproduce it. If you still have this problem, please reopen and write how to reproduce it.
