### ISSUE TITLE
Tag v0.13.0

### ISSUE THREAD

**Issue by ctrochalakis** [geminabox/geminabox#227]
According to rubygems.org[0] v0.13.0 is uploaded but there is no such tag in the repo.

Could you please push the missing bits?

Thanks :)

[0] https://rubygems.org/gems/geminabox

**Comment by cwninja** [comment]
Is there a need for it to be in vX.Y.Z form? I ask as there is a 0.13.0 tag.

**Comment by ctrochalakis** [comment]
Ah, I was using the https://github.com/cwninja/geminabox.git remote instead of geminabox/geminabox :)

Sorry for that @cwninja
