### ISSUE TITLE
Unable to load a proper version of Sinatra (Not sure if this is in Geminabox or Sinatra or something else)

### ISSUE THREAD

**Issue by avecchio** [geminabox/geminabox#228]
Using builder 3.2.2
Using multipart-post 2.0.0
Using httpclient 2.7.1
Using nesty 1.0.2
Using rack 1.6.4
Using tilt 2.0.2
Using bundler 1.11.2
Using faraday 0.9.2
Using rack-protection 1.5.3
Using sinatra 1.4.6
Using geminabox 0.12.4

/usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:113:in `require': unable to find a version of 'sinatra' to activate (Gem::LoadError)
    from /usr/local/lib/ruby/gems/2.3.0/gems/geminabox-0.13.0/lib/geminabox.rb:4:in`<top (required)>'
    from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
    from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in`rescue in require'
    from /usr/local/Cellar/ruby/2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
    from /Users/austin.vecchio/Desktop/vault/box/config.ru:2:in`block in <main>'
    from /usr/local/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:55:in `instance_eval'
    from /usr/local/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:55:in`initialize'
    from /Users/austin.vecchio/Desktop/vault/box/config.ru:in `new'
    from /Users/austin.vecchio/Desktop/vault/box/config.ru:in`<main>'
    from /usr/local/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:49:in `eval'
    from /usr/local/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:49:in`new_from_string'
    from /usr/local/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/builder.rb:40:in `parse_file'
    from /usr/local/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/server.rb:318:in`build_app_and_options_from_config'
    from /usr/local/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/server.rb:218:in `app'
    from /usr/local/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/server.rb:353:in`wrapped_app'
    from /usr/local/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/server.rb:282:in `start'
    from /usr/local/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/lib/rack/server.rb:147:in`start'
    from /usr/local/lib/ruby/gems/2.3.0/gems/rack-2.0.0.alpha/bin/rackup:4:in `<top (required)>'
    from /usr/local/bin/rackup:23:in`load'
    from /usr/local/bin/rackup:23:in `<main>'

**Comment by redrick** [comment]
Hey,

we just ran into same issue you describe. What we did is we updated couple gems on that server recently which was what broke it...
So:

`gem uninstall sinatra` (better uninstall all if you have more without RVM)

and install directly version stated in `.gemspec` here:

`gem install sinatra:1.2.7`

then have a look, in our case we had `rack` updated, so we had to solve that conflict too:
(there were 2 present -> 1.6.0 and 2.0.1)
You only need older one, so we had to delete the older one.

And after that for us everything runs as before :)

**Comment by dforste** [comment]
You also have to `gem uninstall tilt` from what I have seen. It helps if you install the older version of sinatra first and then install geminabox.

**Comment by sonots** [comment]
you are using rack 1.6.4, but loading rack 2.0.0-alpha. it looks wierd.
if you still have this problem, please reopen it.
