### ISSUE TITLE
option to forbid uploading copies of gems that are on rubygems.org

### ISSUE THREAD

**Issue by grosser** [geminabox/geminabox#236]
Regularly seeing people uploading public gems to the internal gem server by accident or to avoid github dependencies, but to avoid confusion / security issues (what does gem install xyz actually install ?) I'd like to block that ... 
@sonots would you accept a PR that adds an optional flag to allow uploading gems that already exist on rubygems.org ?

**Comment by sonots** [comment]
> option to forbid uploading copies 

👍

**Comment by grosser** [comment]
thx, will work on a PR when I got some spare time :D
