### ISSUE TITLE
Uploading via website triggers ENOENT error on windows

### ISSUE THREAD

**Issue by coryallegory** [geminabox/geminabox#237]
geminabox hosted on a Windows Server 2012 R2 instance
When initiating upload via the web UI, response is

Errno::ENOENT at /upload
No such file or directory - /tmp/geminabox.lockfile

![capture](https://cloud.githubusercontent.com/assets/658220/15979215/634c3d10-2f28-11e6-9af1-d415de7effad.PNG)

**Comment by coryallegory** [comment]
Manually creating a c:\tmp directory is a workaround, but should probably be using
```
require 'tmpdir'
temp = Dir.tmpdir() 
```
wherever `\tmp\` is referenced

**Comment by sonots** [comment]
ah, geminabox is using flock. windows server is not supported
