### ISSUE TITLE
Using custom views

### ISSUE THREAD

**Issue by DmitrySharikov** [geminabox/geminabox#238]
Hi there!

What is the best way to use my own html instead deafult?(best way = I don't need monkeypatching)

**Comment by reggieb** [comment]
Have a look at https://github.com/geminabox/geminabox-bootstrap

It shows how the geminabox views can be replaced with another set of views - in this case a bootstrap friendly version.

**Comment by DmitrySharikov** [comment]
@reggieb Thank you! That's what I need!

p.s. Thanks for this awesome gemserver

**Comment by reggieb** [comment]
You're welcome - and @tomlea deserves the credit for Geminabox. I just extended the functionality a little.
