### ISSUE TITLE
HELP: configureable auth for a docker image

### ISSUE THREAD

**Issue by EugenMayer** [geminabox/geminabox#240]
Iam trying to build a slim but configurable docker image to server a as geminabox server for [rancher](http://rancher.com/) / [rancher catalog](http://docs.rancher.com/rancher/latest/en/catalog/). I very new to geminabox and basically doing rather devops.

I have written a conditional configuration file https://github.com/EugenMayer/geminabox-docker/blob/master/config.ru based on things i have found.

It works, but its obviously not very polished and far from optimal.

I though to ask you guys to maybe assist in adjusting it, so this image can be a starting point.

In any way, thank you for your time

**Comment by yuri-karpovich** [comment]
You can try this Docker Image https://hub.docker.com/r/spoonest/geminabox/ .
