### ISSUE TITLE
Bundle install failure

### ISSUE THREAD

**Issue by deadeyejoe** [geminabox/geminabox#241]
Bundle install fails whenever I include my geminabox gem server in the Gemfile, with this error:

> Retrying dependency api due to error (2/4): Bundler::HTTPError Network error while fetching http://gems.dev.edgescan.com/api/v1/dependencies?gems=multi_xml%2Chttparty%2Cmimemagic%2Cmultipart-post%2Chttmultiparty%2Cmulti_json%2Cjbuilder%2Clograge%2Credis%2Credis-namespace%2Cresponders%2Cservice_schema%2Cinfrastructure%2Cmetaclass%2Cmocha%2Cmustache%2Cmysql2%2Cpuma%2Crdoc%2Crspec-support%2Crspec-core%2Crspec-expectations%2Crspec-mocks%2Crspec-rails%2Csdoc%2Cspring%2Csqlite3%2Cweb-console%2Cwebmock

If I comment out my private gem server in the Gemfile, bundle install completes with no problems.

There is an additional puzzling element to this problem: I've only observed it on rbx versions 3.45 and later, if I run bundle install with earlier rbx versions, the geminabox server doesn't cause any problems. I realise that the problem could lie in either bundler or rbx itself, but I thought I'd ask here first since I'm not seeing this problem with the rubygems.org server.

I've made a [gist](https://gist.github.com/deadeyejoe/aadeeb325ce8cef7026f0179b89c94ba) containing the error output when running `bundle install --verbose`, and the output of `bundler env`, let me know if there's any other information I can provide.

**Comment by sonots** [comment]
rubinious is broken, it is not supported
