### ISSUE TITLE
version error

### ISSUE THREAD

**Issue by charlesdbs** [geminabox/geminabox#251]
I use geminabox to my own gem source. But when I execute gem install 

ERROR:  While executing gem ... (TypeError)
    incompatible marshal file format (can't be read)
	format version 4.8 required; 13.10 given

what does this mean？

**Comment by sonots** [comment]
I can not reproduce it. My ruby and gem versions are:

```
$ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin13]
$ gem -v
2.5.1
```

What is yours?

**Comment by sonots** [comment]
No response. Close
