### ISSUE TITLE
Question: Is it possible to proxy for https://rails-assets.org ?

### ISSUE THREAD

**Issue by zerthimon** [geminabox/geminabox#252]
Geminabox is configured to proxy for https://rubygems.org.
Is it possible to cofigure it to proxy for https://rails-assets.org, and how is it done ?

**Comment by rollbrettler** [comment]
Have you tried setting a [mirror in bundler](http://bundler.io/v1.13/man/bundle-config.1.html#MIRRORS-OF-GEM-SOURCES)
```
bundle config mirror.https://rails-assets.org http://localhost:9292
```

**Comment by zerthimon** [comment]
Yep, it proxies to https://rubygems.org: https://github.com/geminabox/geminabox/blob/master/lib/geminabox.rb#L88

When I override the defaults with `Geminabox.ruby_gems_url = ' https://rails-assets.org'` and set the mirror to my host `bundle config mirror.https://rails-assets.org http://localhost:9292` bundler can't find any gems at all:
```
Could not find rails-assets-angular-1.5.8 in any of the sources
```

**Comment by sonots** [comment]
it is not supported
