### ISSUE TITLE
gem inabox command: Ability to set host is broken

### ISSUE THREAD

**Issue by entropicrune** [geminabox/geminabox#256]
The following example is given:
    `gem inabox -g HOST`
       
when used, this complains:

> You didn't specify a gem, looking for one in . and in ./pkg/...
ERROR:  While executing gem ... (Gem::CommandLineError)
    Couldn't find a gem in pkg, please specify a gem name on the command line (e.g. gem inabox GEMNAME)

This command (without the gem) is useful for configuring development environments that are built using Vagrant. I suppose I could use "expect" to script interaction with "gem inabox -c", but wouldn't it be a lot nicer to make the example actually work?

**Comment by sonots** [comment]
I don't understand well.

> the example actually work?

All of examples on README seemed to work expectedly.

```
gem inabox pkg/my-awesome-gem-1.0.gem
gem inabox -c
gem inabox -g HOST
```

**Comment by sonots** [comment]
I gonna close, but please reopen if you can give us more details.
