### ISSUE TITLE
Question on proxy

### ISSUE THREAD

**Issue by baurzhan-konurbayev** [geminabox/geminabox#262]
Hi, guys! This is rather a question than an issue.

I couldn't find a good information on proxy for rubygems.org using geminabox, except configuration steps. Currently I am seeing outgoing connections to rubygems.org, but it should have been already cached due to multiple execution of the same task. I didn't find any single cached gem on the file system, besides gem specifications.

I would be highly appreciated if you could shed light on this mystery.

Many thanks in advance.

**Comment by sonots** [comment]
hmm, it should be cached (downloaded) in data directory of local file system.
if you still have this issue, please reopen it.
