### ISSUE TITLE
Add support for AWS S3 backend

### ISSUE THREAD

**Issue by tmaier** [geminabox/geminabox#264]
> As an admin, I want to reduce administration effort by moving the data layer to S3.

## Scenario 1
* Gems already hosted on S3
* Marhall files already created, saved on S3 (e.g. done by some CI/CD pipeline)
* S3 bucket shall require authorization, using S3 HMAC method
* Upload via geminabox has been disabled with `Geminabox.allow_upload`

## Solution
* User uses `rubygems_proxy` mode to archive this feature
* User configures `ruby_gems_url` to point to the S3
* `path = File.join(ruby_gems_url, *request.path_info) ` (see [proxy/hostess.rb#L62](https://github.com/geminabox/geminabox/blob/master/lib/geminabox/proxy/hostess.rb#L62)) would need to be more flexible to support AWS auth methods. E.g. by getting moved to a separate method, maybe class/gem. The same method would look like this in AWS S3:
  1. Generate URL (see above)
  1. Sign URL
  1. Add HMAC signature as HTTP GET attributes to URL
  1. Download content with HTTP GET request

**Comment by sonots** [comment]
I did not try, but I guess handling atomicity will be complicated and require different logics with local files.

**Comment by sonots** [comment]
related with https://github.com/geminabox/geminabox/issues/77

**Comment by sonots** [comment]
just a interest, but in your scenario, how users will release a gem?

**Comment by tmaier** [comment]
I would use `gem generate_index` (see [docs](http://guides.rubygems.org/command-reference/#gem-generate_index)) to generate the index and upload everything to S3 (for example with [dpl](https://github.com/travis-ci/dpl))
