### ISSUE TITLE
Clicking on delete prompts to delete then downloads gem

### ISSUE THREAD

**Issue by erikanderson** [geminabox/geminabox#265]
On geminabox 0.13.5 and ruby 2.2.7 when I click the Delete button it does not delete the gem but instead downloads it. Anyone else experiencing this?

**Comment by erikanderson** [comment]
Nevermind, this was related to us rewriting http to https in nginx 😞

**Comment by jmhertlein** [comment]
I have the same issue, and am also rewriting http to https in nginx. How did you fix it?

Disabling http->https rewriting is not an option, especially since geminabox loves reverting to http.
