### ISSUE TITLE
gem inabox command: Same configuration different machines, not authorized

### ISSUE THREAD

**Issue by thebravoman** [geminabox/geminabox#270]
The same configuration on two different machines. 
When executing 
```
gem inabox
```

On one of the machines I receive 
```
<html>
<head><title>401 Authorization Required</title></head>
<body bgcolor="white">
<center><h1>401 Authorization Required</h1></center>
<hr><center>nginx/1.8.0</center>
</body>
</html>
```

on the other everything works correctly. 

What should I even look for. Password and users are the same

**Comment by sonots** [comment]
It looks the error is coming from nginx rather than geminabox. check your configuration of nginx

**Comment by thebravoman** [comment]
No, it is not coming from NGinx. The nginx is the same and I am able to login with the browser and with wget. It accepts the user and the password.

Tracked down the problem to the fact that on the second machine (where the project is the same and is just cloned, like on the first machine) the gem inabox command was not taking the configuration from bundle. 

```
bundle config
```
shows the same config on both machines but the second machine I must have the username and the password in the url while on the first machine I could have the username and password in the bundle config. 

Didn`t had the energy to track it why it happens.

**Comment by sonots** [comment]
```
bundle config SOURCE_URL USERNAME:PASSWORD
```

worked effectively with `gem inabox` command in the first machine, and did not work in second machine?

I am not sure, but it probably is not a problem of geminabox because you say it works on the first machine.
