### ISSUE TITLE
Scaling issues with geminabox

### ISSUE THREAD

**Issue by HenluStarke** [geminabox/geminabox#272]
Hi there,
I am representing a company that leverages your geminabox code to proxy rubygems.org as well as serve our proprietary gems. 

We have been encountering numerous timeout issues with regards to concurrency issues on gem installs across our nodes (in excess of 2000 with approximately 104 gem installs per node). Observing the logs leads me to believe that the majority of processing power (we max out all 8 cores on an Intel Xeon E31230) is due to the Gzipping of each individual request.

Are there any plans to provide options to relax the freshness of the gz files?

During my testing I made the following changes to your code:

```
`--- a/lib/geminabox/proxy/splicer.rb`
`+++ b/lib/geminabox/proxy/splicer.rb`
`@@ -12,6 +12,7 @@ module Geminabox`
`       end`

`       def create`
`+        return nil unless necessary?`
`         if data = new_content`
`           f = Tempfile.create('geminabox')`
`           begin`
`@@ -76,6 +77,14 @@ module Geminabox`
`         local_content.to_s + remote_content.to_s`
`       end`
 
`+      def necessary?`
`+        if proxy_file_exists?`
`+          return Time.now - File.mtime(proxy_path) > 3600`
`+        else`
`+          true`
`+        end`
`+      end`
`+`
`     end`
`   end`
` end`
```

The above change allowed me to increase my concurrency from 8 nodes installing 104 gems to over a 100 nodes installing 104 gems concurrently.

The purpose of my change was just to relax the freshness of the list of gems from rubygems.org to 1 hour, as we have no requirement on our infrastructure to always get the latest list of ruby gems available, i.e if the list is an hour old or even older, it would suffice as a proxy.

Please note that I did not spend a large amount of time on the code or testing thereof, it was merely a prototype. I am more than happy to submit a merge request with the above code, if you feel that it will be helpful. If you would like to know more about our scalling issues/requirements, please dont hesitate to drop me a message.

**Comment by sonots** [comment]
I recommend to serve files of https://github.com/geminabox/geminabox/blob/a94ccc7bcc36f320064e7a0aec6f5c01936de4d4/lib/geminabox/proxy/hostess.rb#L16-L53 with nginx where https://github.com/geminabox/geminabox/blob/a94ccc7bcc36f320064e7a0aec6f5c01936de4d4/lib/geminabox/proxy/hostess.rb#L16-L25 are your concerns.

It should be possible to configure nginx to access geminabox only one time during one hour with cache feature. I am glad if someone could paste an example configuration here.

**Comment by MichaelSp** [comment]
Here is the configuration we are using:

```
$cat /etc/nginx/nginx.conf
user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}

$cat  /etc/nginx/conf.d/default.conf
gzip_types text/plain text/css application/javascript application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;
log_format vhost '$host $remote_addr - $remote_user [$time_local] '
                 '"$request" $status $body_bytes_sent '
                 '"$http_referer" "$http_user_agent"';
access_log off;
# HTTP 1.1 support
proxy_http_version 1.1;
proxy_buffering off;
proxy_set_header Host $http_host;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection $proxy_connection;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $proxy_x_forwarded_proto;
proxy_set_header X-Forwarded-Ssl $proxy_x_forwarded_ssl;
proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
# Mitigate httpoxy attack
proxy_set_header Proxy "";

upstream gemserver {
				## Can be connect with "geminabox_default" network
			# geminabox_server_1
			server 172.20.0.2:9292;
}
server {
	server_name gemserver;
	listen 80 ;
	access_log /var/log/nginx/access.log vhost;
	location / {
		proxy_pass http://gemserver;
                
		proxy_cache_key $host$uri$is_args$args;
		proxy_cache my-cache;
		proxy_cache_valid  200 302  60m;
		proxy_cache_valid  404 1m;
		proxy_buffering on;

		add_header X-Proxy-Cache $upstream_cache_status;
	}
}

$ cat /etc/nginx/conf.d/cache.conf

proxy_cache_path  /var/cache/nginx  levels=1:2    keys_zone=my-cache:10m inactive=24h  max_size=1g;
```
