### ISSUE TITLE
http_client.ssl_config.verify_mode = OpenSSL::SSL::VERIFY_NONE should be configurable

### ISSUE THREAD

**Issue by pascal-hofmann** [geminabox/geminabox#274]
Why does geminabox not verify SSL certificates? IMHO this should be configurable, with "verify" as the default.

**Comment by reggieb** [comment]
The main problem is backward compatibility. 

However, one of the main drivers of splitting out the HTTP adapter from the main code, was to allow alternative HTTP implementations to be dropped in easily. If you look at the [default adapter](https://github.com/geminabox/geminabox/blob/master/lib/geminabox/http_adapter/http_client_adapter.rb), you should see how to modify this to work the way you want. So roll your own adapter, and as explained in the README, you can then configure Geminabox to use the modified adapter with the SSL configuration you desire.

**Comment by pascal-hofmann** [comment]
It's a trade-off between backwards compatibility and security. IMHO security is more important and there should be a new version with safe defaults and a guide on how to get old behavior back with an explicit warning about it's security implications.

Optimal solution would be to allow a configurable list of domains for which certificate verification is skipped. This way users could selectively whitelist their local, trustworthy hosts.
