### ISSUE TITLE
Is it possible to set an upstream server?

### ISSUE THREAD

**Issue by MichaelStankiewicz** [geminabox/geminabox#275]
I have a need to have a geminabox instance in a ringed environment that does not have direct access to the internet.  The idea is that I would have an internal geminabox instance that points to an 'upstream' geminabox instance which does have direct access to the internet.  

Is this possible in the most recent version of geminabox?  If it is, how would I set my geminabox downstream instance to point to my upstream instance?  Is it as simple as setting the downstream server's gem source to point to my upstream geminabox instance?

If this feature is not available, are there plans to enable this functionality?  I'd also be curious to understand if others require the same functionaliy.

**Comment by sonots** [comment]
https://github.com/geminabox/geminabox/pull/231/files

    Geminabox.ruby_gems_url
    Geminabox.bundler_rubygems_url

are available. please let me know if it is still not sufficient.
