### ISSUE TITLE
Fips support

### ISSUE THREAD

**Issue by robertocortiz** [geminabox/geminabox#277]
After we install geminabox, and attach our machines to this server, whenever we attempt to install a gem we get this MD5 error, 
```
"HEAD /api/v1/dependencies HTTP/1.1" 200 - 0.0014
md5_dgst.c(78): OpenSSL internal error, assertion failed: Digest MD5 forbidden in FIPS mode!
Aborted (core dumped)
```
because our systems are running with fips mode turned on, is this something that is being looked at, so openssl libraries can be configurable in the server setup?

**Comment by sonots** [comment]
openssl library is built-in library of ruby.
you probably are able to configure path of openssl library when you build ruby.

**Comment by sonots** [comment]
This is not an issue of geminabox, so let me close.
