### ISSUE TITLE
Internal Server Error 500 Registering Source

### ISSUE THREAD

**Issue by MichaelStankiewicz** [geminabox/geminabox#284]
I'm receiving the following error when attempting to add my gem-in-a-box mirror as a source on my managed nodes:

```
gem source --add http://gems.domain.com:9292
Error fetching http://gems.domain.com:9292:
        bad response Internal Server Error 500 (http://gems.domain.com:9292/specs.4.8.gz)
```

What's strange is, there is a specs.4.8.gz file located under the root of my Geminabox.data folder location, so I don't know why this is not working properly.  Further, I can reach the server over the web GUI interface from my nodes, so it's not a connectivity issue.

Here is what my config.ru file looks like:

```
require "rubygems"
require "geminabox"

Geminabox.data = "/srv/geminabox/gems"

Geminabox.rubygems_proxy = true
Geminabox.allow_remote_failure = true

run Geminabox::Server
```

**Comment by sonots** [comment]
Could you paste stacktrace which should be printed on server?

**Comment by sonots** [comment]
No response. Please reopen and paste stacktrace if you still have the problem. If you can provide how to reproduce, it is very nice.

**Comment by MichaelStankiewicz** [comment]
Thanks for the reply.  This error is occurring on my Windows client, not the server.  Can you provide a method for retrieving the relevant backend details from the server?

**Comment by sonots** [comment]
Are you not the one who is managing your geminabox server? You should ask to your administrator.

**Comment by MichaelStankiewicz** [comment]
No.  I am the one managing the box.

**Comment by sonots** [comment]
Please report the issue to your admin. I need to discuss with him.

**Comment by MichaelStankiewicz** [comment]
But I am the admin.  I own the box.

**Comment by sonots** [comment]
Okay. You should be able to see the error on STDOUT or STDERR of your server process

**Comment by MichaelStankiewicz** [comment]
Ok, thanks.  I currently have the app running as a service.  I assume that I would need to change this so that the process is not running as a service in order to see this output?

**Comment by sonots** [comment]
I am not sure how you are daemonizing your process, but for example, if you are using systemd, you can configure as `StandardOutput=journal` to see the stdout via journalctl. You can see https://www.freedesktop.org/software/systemd/man/systemd.exec.html for more ways and details.

**Comment by MichaelStankiewicz** [comment]
Exception `NoMethodError' at /usr/local/rvm/gems/ruby-1.9.3-p551/gems/geminabox-0.13.5/lib/geminabox/proxy/splicer.rb:16 - undefined method `create' for Tempfile:Class
2017-10-20 10:25:38 - NoMethodError - undefined method `create' for Tempfile:Class:
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/geminabox-0.13.5/lib/geminabox/proxy/splicer.rb:16:in `create'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/geminabox-0.13.5/lib/geminabox/proxy/splicer.rb:10:in `make'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/geminabox-0.13.5/lib/geminabox/proxy/hostess.rb:70:in `splice_file'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/geminabox-0.13.5/lib/geminabox/proxy/hostess.rb:21:in `block (2 levels) in <class:Hostess>'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `call'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.8/lib/sinatra/base.rb:1611:in `block in compile!'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `[]'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.8/lib/sinatra/base.rb:994:in `route_eval'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.8/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.8/lib/sinatra/base.rb:1015:in `block in process_route'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `catch'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.8/lib/sinatra/base.rb:1013:in `process_route'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.8/lib/sinatra/base.rb:973:in `block in route!'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `each'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.8/lib/sinatra/base.rb:972:in `route!'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.8/lib/sinatra/base.rb:1085:in `block in dispatch!'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.8/lib/sinatra/base.rb:1082:in `dispatch!'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `block in call!'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `block in invoke'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `catch'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.8/lib/sinatra/base.rb:1067:in `invoke'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.8/lib/sinatra/base.rb:907:in `call!'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.8/lib/sinatra/base.rb:895:in `call'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.6.8/lib/rack/nulllogger.rb:9:in `call'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.6.8/lib/rack/head.rb:13:in `call'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.8/lib/sinatra/show_exceptions.rb:25:in `call'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.6.8/lib/rack/nulllogger.rb:9:in `call'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.6.8/lib/rack/head.rb:13:in `call'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.6.8/lib/rack/methodoverride.rb:22:in `call'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.8/lib/sinatra/show_exceptions.rb:25:in `call'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.8/lib/sinatra/base.rb:182:in `call'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.8/lib/sinatra/base.rb:2013:in `call'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `block in call'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.8/lib/sinatra/base.rb:1787:in `synchronize'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.8/lib/sinatra/base.rb:1487:in `call'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.6.8/lib/rack/tempfile_reaper.rb:15:in `call'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.6.8/lib/rack/lint.rb:49:in `_call'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.6.8/lib/rack/lint.rb:37:in `call'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.6.8/lib/rack/showexceptions.rb:24:in `call'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.6.8/lib/rack/commonlogger.rb:33:in `call'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.8/lib/sinatra/base.rb:219:in `call'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.6.8/lib/rack/chunked.rb:54:in `call'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.6.8/lib/rack/content_length.rb:15:in `call'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/thin-1.7.2/lib/thin/connection.rb:86:in `block in pre_process'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/thin-1.7.2/lib/thin/connection.rb:84:in `catch'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/thin-1.7.2/lib/thin/connection.rb:84:in `pre_process'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/thin-1.7.2/lib/thin/connection.rb:53:in `process'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/thin-1.7.2/lib/thin/connection.rb:39:in `receive_data'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run_machine'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/eventmachine-1.2.5/lib/eventmachine.rb:194:in `run'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/thin-1.7.2/lib/thin/backends/base.rb:73:in `start'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/thin-1.7.2/lib/thin/server.rb:162:in `start'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.6.8/lib/rack/handler/thin.rb:19:in `run'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.6.8/lib/rack/server.rb:287:in `start'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.6.8/lib/rack/server.rb:148:in `start'
        /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.6.8/bin/rackup:4:in `<top (required)>'
        /usr/local/rvm/gems/ruby-1.9.3-p551/bin/rackup:23:in `load'
        /usr/local/rvm/gems/ruby-1.9.3-p551/bin/rackup:23:in `<main>'
        /usr/local/rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
        /usr/local/rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
Exception `NoMethodError' at /usr/local/rvm/gems/ruby-1.9.3-p551/gems/sinatra-1.4.8/lib/sinatra/base.rb:1113 - undefined method `create' for Tempfile:Class
10.167.25.36 - - [20/Oct/2017:10:25:38 -0400] "GET /specs.4.8.gz HTTP/1.1" 500 210892 41.2163

**Comment by MichaelStankiewicz** [comment]
I was able to use rackup --debug to get the details.  I think the above should work for tracking down the issue.  It appears that the problem is this **NoMethodError** exception.

**Comment by sonots** [comment]
Thank you for the log.
Geminabox does not support ruby 1.9.3. Upgrading to ruby >= 2.2 should fix your problem.

**Comment by MichaelStankiewicz** [comment]
Thanks.  This upgrading Ruby to 2.2.0 got me passed the problem.
