### ISSUE TITLE
Add reasonableness check to the gem install pull

### ISSUE THREAD

**Issue by jmellor** [geminabox/geminabox#285]
We have several times been hit by a geminabox outage, caused by a dev stupidly asking to pull down all gems.  Since our geminabox is configured as a cache for upstream, this pulls all of upstream through geminabox, resulting in a truly massive cache and download that then takes down the geminabox service.
The first noted symptom is a permanent 100% processor looping while performing the next Marshal indexing after the "event".  Recovery does not seem possible, except by going to backups.

Please add a "reasonableness" check for the pull request, and reject any unreasonable requests.

**Comment by sonots** [comment]
Did you find the defective gem? If you can provide the information, I can deeply investigate it.

**Comment by sonots** [comment]
1. Number of web concurrency can be controlled by your server, like 4 concurrent processes with unicorn server.
2. reindex should not be ran concurrently now https://github.com/geminabox/geminabox/pull/276/files. Do you use the latest version and do you still get multiple reindexes concurrently?

**Comment by jmellor** [comment]
We were running a release from January 2017 originally.  Yes, it ran multiple reindex operations simultaneously.  On the advise of Yuriy Karovich (the docker image creator), we switched up to the 0.13.5 (latest) version of the spoonest/geminabox docker image that instead uses rackup, as a first attack in fixing the issue.  This image was just released 2 weeks ago, and has the latest geminabox instead of the 9-month-old version.  Unfortunately, this did not resolve the problem.

**Comment by sonots** [comment]
The latest is 0.13.9.

**Comment by sonots** [comment]
As you state at https://github.com/geminabox/geminabox/issues/286, the root cause is by a defective gem. So, it sounds that the "reasonable" check means to reject such a defective gem.
