### ISSUE TITLE
Error downloading Gem from internal Gem mirror.

### ISSUE THREAD

**Issue by MichaelStankiewicz** [geminabox/geminabox#287]
I've successfully registered my client with my gem-in-a-box mirror.  I execute the following command to download a gem from the server:

gem install %gem%

After some minutes pass, the client returns the following:

`ERROR:  Could not find a valid gem '%gem%' (>= 0) in any repository`

On the gem mirror server, the following is being logged:

```
10.167.25.36 - - [20/Oct/2017:11:33:57 -0400] "GET /latest_specs.4.8.gz HTTP/1.1" 200 1172519 1.6340
Exception `WEBrick::HTTPStatus::EOFError' at /usr/local/rvm/rubies/ruby-2.2.6/lib/ruby/2.2.0/webrick/httpserver.rb:80 - WEBrick::HTTPStatus::EOFError
```

**Comment by sonots** [comment]
The error is occurred at https://github.com/ruby/ruby/blob/v2_2_6/lib/webrick/httpserver.rb#L80.

Referring http://blade.nagaokaut.ac.jp/cgi-bin/scat.rb/ruby/ruby-talk/142285, the `sock.eof?` occurs when `client has closed its side of the connection.`

I think "After some minutes pass" is too long, and the gem client timeout-ed.

**Comment by sonots** [comment]
This must be a configuration error.
Paste your configuration of geminabox, then I may be able to help you.
Also, I recommend you to use a faster web server such as unicorn or puma rather than webrick.

**Comment by sonots** [comment]
Also,

```
ERROR: Could not find a valid gem '%gem%' (>= 0) in any repository
```

should be correct because a gem named '%gem%' does not exist in the world.

**Comment by MichaelStankiewicz** [comment]
I just substituted that text as a placeholder; a _real_ gem was included in the original command, so this really has nothing to do with the error.  And to add, the gem in question is actually located on the internal mirror.

Below are the contents of my config.ru file:

```
require "rubygems"
require "geminabox"

Geminabox.data = "./gems"

Geminabox.rubygems_proxy = true
Geminabox.allow_remote_failure = true

run Geminabox::Server
```

**Comment by MichaelStankiewicz** [comment]
Sorry, please close this issue.  This was user error on my part :).  I had misspelled the gem name in my install command.

Apologies for wasting your time with this one.
