### ISSUE TITLE
Use relative URLs instead of full URLS so geminabox will work behind an HTTPS proxy

### ISSUE THREAD

**Issue by urkle** [geminabox/geminabox#292]
Currently I have geminabox configured to run behind an https proxy. However the geminabox UI creates full urls like http://mygem.server.com/upload  etc.. which when performing actions will yield a browser warning that the url is not secure.

The reason that the URLs are generated incorrectly is due to how rack specifies the "ssl?" method (which is aliased to secure? by sinatra and used by sinatra's URL method to know what scheme to use when building urls).  This method does not take into account proxies at all.

ideally geminabox simply should not be providing http://mygem.server.com at all in the links/form actions.. That is we do not need to pass any of the URLS through the sinatra "url" helper at all. This will workaround the deficiencies in the rack ssl? method

**Comment by tmaier** [comment]
link to relevant sinatra uri method: https://github.com/sinatra/sinatra/blob/b4aaf1c43aa87936846a863a51beac6fe27892f6/lib/sinatra/base.rb#L286-L300

I see two ways:

## 1) set `absolute` to `false` in all calls to `url`.
This means the sinatra helper will generate relative url. We keep using the helper

## 2) Check your Reverse Proxy configuration

One way could be to preserve the request url (with protocol), e.g. https://stackoverflow.com/questions/5834025/how-to-preserve-request-url-with-nginx-proxy-pass
or to rewrite the body of the response, e.g. http://nginx.org/en/docs/http/ngx_http_sub_module.html

@urkle,  could you please check both methods and provide a pull request if you see (1) as viable?

**Comment by urkle** [comment]
I finally managed to get it to behave by having my proxy explicitly set  X-Forwarded-Scheme as 'https'   I tried doing the rewriting of the body initially but that ended up rewriting too much. (Causing all of the data payloads to get corrupted so rubygems would not install anything).

**Comment by tmaier** [comment]
Good to hear :)

Does this mean this issue can be closed?

**Comment by urkle** [comment]
Yeah, unless we want to add in some documentation to the readme on how to set that up properly.

**Comment by sonots** [comment]
let me close
