### ISSUE TITLE
Please release gem version 1.0.1 to rubygems.org

### ISSUE THREAD

**Issue by tmaier** [geminabox/geminabox#306]
The changelog and git tags state that there is a version 1.0.1.

But https://rubygems.org/gems/geminabox lists 1.0.0 as the most recent version.

Can you please release the latest version to rubygems?

Thanks

**Comment by sonots** [comment]
Thank you for letting me know.

It is wierd. I use `rake release` command to release, and it will automatically tag and push to rubygems. At that time, it tagged, but it seemed it did not release to rubygems.

I again released v1.0.1, and now it should be fine.

**Comment by tmaier** [comment]
Thank you very much :)
