### ISSUE TITLE
Question: Is it possible to set a disk usage limit?

### ISSUE THREAD

**Issue by wpp** [geminabox/geminabox#308]
Hi,

Thank you very much for this library. I'm wondering if there is a way to possibly limit the disk usage, especially when enabling the proxy setting?

I'm sorry if I missed this but couldn't find anything in the README and issues.

Cheers

**Comment by sonots** [comment]
geminabox itself does not have such feature.

**Comment by wpp** [comment]
Thanks for the quick response.

Can you share your experiences on growing cache data-directories (Geminabox.data)? How do you deal with them? Cron job?

**Comment by sonots** [comment]
I simply assign large size of disk, and monitor it with percentile.

I examined actual data size which we (my company) used. It seemed 4.6GB.

**Comment by sonots** [comment]
Let me close.
