### ISSUE TITLE
Documentation server?

### ISSUE THREAD

**Issue by ghost** [geminabox/geminabox#309]
Any chance you'd be willing to extend geminabox to support versioned documentation for gems? My workplace has a bunch of internal gems which we host on geminabox and we'd love to have a persistent set of documentation for each version of each gem. Geminabox seems like the logical place to put that.

Alternately, could you support a plugin API that would have hooks for the upload process such that I could shim in my own documentation handling?

**Comment by riddley** [comment]
What release will #307 be included in? Do you have an estimate for when that release will go live?
