### ISSUE TITLE
High availability & Load balancing with geminabox

### ISSUE THREAD

**Issue by nitin02** [geminabox/geminabox#313]
When using geminabox for production deployments, It is necessary that the uptime of the gem server remains very high to reach the desired SLAs for applications which use it, and that it can scale as more apps use it.

What is the ideal way to implement HA with geminabox? Something like, multiple instances running geminabox, which are accessed with a load balancer, while the persistent storage made independently accessible.

**Comment by sonots** [comment]
I setup two Geminabox servers with a load balancer, and NFS for persistent storage. But, this is not a perfect solution.

Geminabox uses flock https://github.com/geminabox/geminabox/blob/bf71f9b8723087c6990644b1093193b7484fd049/lib/geminabox/server.rb#L68, so this implementation is safe on multiple processes, but not safe on multiple servers. We need to customize it to use distributed mutex with redis, or something.

You may keep one server as a cold standby to avoid this problem.
