### ISSUE TITLE
Error (404) when running 'bundle install --verbose' in combination with geminabox-Server

### ISSUE THREAD

**Issue by HansaExport** [geminabox/geminabox#323]
Hi,

we run a geminabox-Server in our company. When deleting the Gemfile.lock and running `bundle install --verbose` on our projects, we're getting the following error:

```
Running 'bundle install --verbose' with bundler 2.0.1
Found changes from the lockfile, re-resolving dependencies because bundler is unlocking gems: (OUR_GEM), ruby
HTTP GET http://OUR_GEMSERVER:3000/versions
HTTP 404 Not Found http://OUR_GEMSERVER:3000/versions
Bundler::Fetcher::FallbackError: Net::HTTPNotFound
C:/Ruby24/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/fetcher/downloader.rb:40:in 'fetch'
  C:/Ruby24/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/fetcher/compact_index.rb:117:in 'call'
  C:/Ruby24/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/compact_index_client/updater.rb:53:in 'block in update'
  C:/Ruby24/lib/ruby/2.4.0/tmpdir.rb:89:in 'mktmpdir'
  C:/Ruby24/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/compact_index_client/updater.rb:31:in 'update'
  C:/Ruby24/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/compact_index_client.rb:82:in 'update'
  C:/Ruby24/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/compact_index_client.rb:69:in 'update_and_parse_checksums!'
  C:/Ruby24/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/fetcher/compact_index.rb:69:in 'available?'
  C:/Ruby24/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/fetcher/compact_index.rb:16:in 'call'
  C:/Ruby24/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/fetcher/compact_index.rb:16:in 'block in compact_index_request'
  C:/Ruby24/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/fetcher.rb:158:in 'use_api'
  C:/Ruby24/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/source/rubygems.rb:382:in 'block in api_fetchers'
  C:/Ruby24/lib/ruby/gems/2.4.0/gems/bundler-2.0.1/lib/bundler/source/rubygems.rb:382:in 'select'
[...]
```

The Gemfile only uses our geminabox-Server:

`
source 'http://OUR_GEMSERVER:3000'
[...]
`

The path to /versions on our geminabox-Server does not exist, so we're getting this error. 

What could we do, what is wrong?

**Comment by keithrbennett** [comment]
I am experiencing this too. Could you reopen and look into this please?

**Comment by keithrbennett** [comment]
I downloaded the source code and was unable to find a route for `versions`, nor any other code that looked like it was producing that list. I just pointed my browser to https://rubygems.org/versions, and got a list with a header that indicated that the list was generated over a month ago...so maybe it's bundler that is doing the wrong thing relying on it? I don't know.

**Comment by keithrbennett** [comment]
I just uninstalled bundler 2.3.x gems and have only 2.2.14 remaining. Now when I run `bundle`, there is no delay in execution.

The verbose output indicates that it too is trying to find a list of versions, and fails, but the output no longer includes the verbose and slow output it did before.

I'm now suspecting it's a bundler issue and not a Gem-in-a-Box issue.

That said, if providing a versions list is doable and would eliminate the problem (I have no idea if it would), that might be a nice-to-have. (Not volunteering though! :) and I appreciate the value of contributors' time.)

**Comment by skaes** [comment]
https://andre.arko.net/2014/03/28/the-new-rubygems-index-format/ seems to be the only documentation available on the new index format.

**Comment by keithrbennett** [comment]
I think the PR at https://github.com/geminabox/geminabox/pull/435 is a better place for my issue. Feel free to re-close this issue.

Thanks, @skaes .
