### ISSUE TITLE
Compare with GitHub Package

### ISSUE THREAD

**Issue by sonots** [geminabox/geminabox#333]
GitHub supports GitHub Package to release private gem nowadays. You may not need to host your own private rubygems server with geminabox. Check it out.
https://help.github.com/github/managing-packages-with-github-packages/configuring-rubygems-for-use-with-github-packages

**Comment by sonots** [comment]
I am glad if anyone reports comparison between Github Package and Geminabox.

**Comment by micheelengronne** [comment]
It defeats the purpose of an opensource project. It makes your dev very dependant on Github.
