### ISSUE TITLE
Please make breaking changes obvious in the Changelog

### ISSUE THREAD

**Issue by sriedel** [geminabox/geminabox#347]
I've just spend an hour trying to figure out why we are no longer caching remote gems on our geminabox instance. After ruling out the local server setup, gem and bundler configurations (the usual suspects), I only found the note about a breaking change in the actually commit messages. An innocent `enhancement` in a changelog without an explicit pointer to breaking changes in the behaviour left me initially blind to the fact that I needed to check what was actually changed and update our geminabox config.

**Comment by tnir** [comment]
@sriedel What version did you run into that problem?

**Comment by tnir** [comment]
No specific answer replied. Closing.
