### ISSUE TITLE
1.3.0 no longer caching gem versions that already have a local cached version present

### ISSUE THREAD

**Issue by sriedel** [geminabox/geminabox#348]
After updating from 1.2.0 to 1.3.0, I have the issue that newer versions of remote (i.e. gems from rubygems.org) are no longer cached by geminabox, despite other versions of this gem already being present.

E.g. 1.2.0 the local gem repository had activesupport version 6.0.3.4 and 6.1.0, which it has previously cached and retrieved from rubygems.org. After the update to 1.3.0 geminabox will not cache activesupport 6.0.3.5 locally.

The expectation would be that 6.0.3.5 be cached locally, as activesupport has already had other versions cached. Ideally without disabling the new security enhancement. 

Would deleting all cached-from-rubygems.org-gems in the gem repository restore the expected behaviour?

**Comment by dgsangoma** [comment]
It looks like https://github.com/geminabox/geminabox/pull/345 should hopefully fix this whenever it's merged / released.
