### ISSUE TITLE
Unable to install gem with another version

### ISSUE THREAD

**Issue by atiffarrukh** [geminabox/geminabox#350]
Geminabox version: 1.3.0
I have set-up Geminabox, things were going well, till I tried to install a gem, currently with version N on my geminabox, with N+1, I got the following error
`ERROR:  Could not find a valid gem 'GEM' (= N+1) in any repository` 
For example I have oauth2 v 1.3.1 current in my geminabox. When I tried to install version 1.4.7. I got
`ERROR:  Could not find a valid gem 'oauth2' (= 1.4.7) in any repository`

First I thought it might some connectivity issue with `rubygems`, so I tried to install a gem that was not currently in my geminabox (simple-random) and it was installed successfully. Then I tried to installed a different version of it, the same error occurred.

My config.ru is as follows
```
require "rubygems"
require "geminabox"
require 'rack/auth/basic'

use Rack::Auth::Basic, "Protected Area" do |username, password|
  username == "obscured" && password == "obscured"
end

Geminabox.data = "/home/ubuntu/geminabox/data" 
Geminabox.rubygems_proxy = true

use Rack::Session::Pool, expire_after: 1000 # sec
use Rack::Protection
run Geminabox::Server
```

**Comment by zinga666** [comment]
Hi,

I can confirm this since I am having the very same issue with version 1.3.0 as well.

I am using
```
Geminabox.rubygems_proxy = true
Geminabox.allow_remote_failure = true
```
in the config.

**Comment by mowings** [comment]
Same same -- any word on this?

**Comment by platbr** [comment]
Same problem here.

**Comment by zinga666** [comment]
[This](https://github.com/geminabox/geminabox/pull/345#issuecomment-1040165860) fixed it for me.
