### ISSUE TITLE
SSLtest fails only on Ubuntu 20.04 (focal)

### ISSUE THREAD

**Issue by tnir** [geminabox/geminabox#359]
`SSLTest#test_method` in `bundle exec rake test:integration` fails on the following conditions.

1. Fails only on Ubuntu 20.04, not on 18.04, 16.04:
   - https://travis-ci.com/github/tnir/geminabox/builds/230952625
2. Fails only with Ruby 2.4 through 3.0 even on Ubuntu 20.04 while succeeds with Ruby 2.2/2.3 on Ubuntu 20.04
   - https://github.com/tnir/geminabox/actions/runs/973989398
   - (on `Travis-ci.com`, it is not so easy to get Ruby 2.2/2.3 on `dist: focal`)

#### Error log

```
  1) Failure:
SSLTest#test_method: can push example  [/home/travis/build/tnir/geminabox/test/test_support/geminabox_test_case.rb:53]:
Expected /Gem .* received and indexed./ to match "ERROR:  While executing gem ... (HTTPClient::ConnectTimeoutError)\n    execution expired\nPushing example-1.0.0.gem to https://127.0.0.1:44157/...\n".
```

**Comment by ahorek** [comment]
the error is ```OpenSSL::SSL::SSLError: SSL_CTX_use_certificate: ee key too small```
