### ISSUE TITLE
Slow gem install with ruby 3+

### ISSUE THREAD

**Issue by seandilda** [geminabox/geminabox#369]
I'm running geminabox 1.4.1 as a rubygems proxy.   I recently realized that running a 'gem install' against my proxy is much slower on ruby 3.x than it is with 2.x

For testing, I ran the command `time gem install --clear-sources --source https://<internal geminabox url> ast` on the following docker images with the following results:

| Docker image | Time |
| --- | --- |
| ruby:2.7-alpine | 0m 0.81s |
| ruby:3.0-alpine | 0m 59.67s |
| ruby:3.1-alpine | 1m 0.48s |

Checking the logs from geminabox, I found the following with 2.7:

```
10.13.30.36 - - [03/Mar/2022:19:38:30 +0000] "GET /api/v1/dependencies?gems=ast HTTP/1.1" 200 496 0.2240
10.13.30.36 - - [03/Mar/2022:19:38:30 +0000] "GET /quick/Marshal.4.8/ast-2.4.2.gemspec.rz HTTP/1.1" 200 480 0.0084
10.13.30.36 - - [03/Mar/2022:19:38:30 +0000] "GET /gems/ast-2.4.2.gem HTTP/1.1" 200 11776 0.0063
```

And with 3.0:

```
10.13.30.36 - - [03/Mar/2022:19:48:01 +0000] "HEAD / HTTP/1.1" 200 572715 0.8438
10.13.30.36 - - [03/Mar/2022:19:48:01 +0000] "GET /info/ast HTTP/1.1" 404 13 0.0033
10.13.30.36 - - [03/Mar/2022:19:48:02 +0000] "GET /prerelease_specs.4.8.gz HTTP/1.1" 200 384789 1.2288
10.13.30.36 - - [03/Mar/2022:19:48:10 +0000] "GET /specs.4.8.gz HTTP/1.1" 200 4542076 7.1350
10.13.30.36 - - [03/Mar/2022:19:48:56 +0000] "GET /quick/Marshal.4.8/ast-2.4.2.gemspec.rz HTTP/1.1" 200 480 0.0050
10.13.30.36 - - [03/Mar/2022:19:48:56 +0000] "GET /quick/Marshal.4.8/ast-1.0.0.gemspec.rz HTTP/1.1" 200 445 0.0047
10.13.30.36 - - [03/Mar/2022:19:48:56 +0000] "GET /quick/Marshal.4.8/ast-1.0.1.gemspec.rz HTTP/1.1" 200 447 0.0047
10.13.30.36 - - [03/Mar/2022:19:48:56 +0000] "GET /quick/Marshal.4.8/ast-1.0.2.gemspec.rz HTTP/1.1" 200 458 0.0040
10.13.30.36 - - [03/Mar/2022:19:48:56 +0000] "GET /quick/Marshal.4.8/ast-1.1.0.gemspec.rz HTTP/1.1" 200 454 0.0050
10.13.30.36 - - [03/Mar/2022:19:48:56 +0000] "GET /quick/Marshal.4.8/ast-2.0.0.gemspec.rz HTTP/1.1" 200 497 0.0046
10.13.30.36 - - [03/Mar/2022:19:48:56 +0000] "GET /quick/Marshal.4.8/ast-2.1.0.gemspec.rz HTTP/1.1" 200 517 0.0039
10.13.30.36 - - [03/Mar/2022:19:48:56 +0000] "GET /quick/Marshal.4.8/ast-2.2.0.gemspec.rz HTTP/1.1" 200 517 0.0039
10.13.30.36 - - [03/Mar/2022:19:48:56 +0000] "GET /quick/Marshal.4.8/ast-2.3.0.gemspec.rz HTTP/1.1" 200 517 0.0038
10.13.30.36 - - [03/Mar/2022:19:48:56 +0000] "GET /quick/Marshal.4.8/ast-2.4.0.gemspec.rz HTTP/1.1" 200 520 0.0042
10.13.30.36 - - [03/Mar/2022:19:48:56 +0000] "GET /quick/Marshal.4.8/ast-2.4.1.gemspec.rz HTTP/1.1" 200 477 0.0038
```

It appears the the lack of the '/info/<gemname>' API is causing the `gem` command to fall back to a slow path.  Its also worth noting that the `gem` command is using up 100% CPU during this, likely parsing through the `specs.4.8.gz` file.

**Comment by conathan** [comment]
I have seen this as well.

in our case, Patching geminabox 1.4.1 with https://github.com/geminabox/geminabox/pull/353 worked well,

and then if using this as a rubygems mirror, Geminabox.rubygems_proxy_merge_strategy = :remote_gems_take_precedence_over_local_gems (fixes https://github.com/geminabox/geminabox/pull/345 in such a scenario)
* Unrelated, but mentioning it as we got tripped up using :combine_local_and_remote_gem_versions for a rubygems server and the above patchset, which 404's on /info links

**Comment by seandilda** [comment]
Updating per the bot's request.

Looks like #435 may be a possible fix for this once it is ready.

**Comment by skaes** [comment]
@seandilda you're correct #435 will fix it.
