### ISSUE TITLE
Release plan 2022

### ISSUE THREAD

**Issue by tnir** [geminabox/geminabox#381]
@tomlea @kerrizor @reggieb @sonots @pipt What do you have any plan to release newer commits to `RubyGems.org`?

@tnir merged #361 to the default branch, which causes dropping support for IE6, IE7, and IE8 😁, with @rikas's help 🙏 . So we can go forward as geminabox 2.0 while @rikas tagged it as 1.4.2 only on Git repo.

# Other fixes
- Fix a runtime bug with the existence of Faraday v2 in Ruby 2.6+ #360 
- Deprecate RubyGems index: #365
- Ruby 3.1 support: #378

# Chores
- #358 

### Updates on tests
- #363
- #372
- #376

cc @deivid-rodriguez for helping them as a member of @rubytogether

**Comment by tnir** [comment]
Not sure @rubytogether wants to maintain this gem though as they have [rubygems/gemstash](https://github.com/rubygems/gemstash).

> cc @deivid-rodriguez for helping them as a member of https://github.com/rubytogether

**Comment by deivid-rodriguez** [comment]
I want to help out mainly because I want https://github.com/geminabox/geminabox/pull/353 to move forward. Bundler & RubyGems now use more modern APIs provided by rubygems.org, but custom servers like geminabox have not yet implemented them. This is already causing correctness and performance issues and it forces us to maintain code just for backwards compatibility with custom servers that we would like to deprecate in the future.

Regarding gemstash, yes, that's under the rubygems namespace so we're in theory in charge of it but we're also lacking resources to maintain it :(

**Comment by skaes** [comment]
We would greatly appreciate https://github.com/geminabox/geminabox/pull/353 moving forward, as the lack of  support for the compact index API has quite some performance impact. Since rubygems release version 3.3.5 (which includes [this PR](https://github.com/rubygems/rubygems/pull/5256)), bundler will download dependency information for each version of a gem in the dependency graph sequentially. This can result in bundler operations taking a minute or more to complete.

**Comment by tomlea** [comment]
Hi, just dropping in to say hello, and see if we can get things moving.

First, loving all the love this project is getting all of a sudden!

I'm the original author, but sadly no longer use ruby on a day to day basis, don't use GemInABox as part of my day to day, so don't consider myself a good candidate for maintainer, stay mostly quiet, but still hang on as a "backstop", for when others move on, or things get stuck.

Looks like it's time for me to do some backstopping.

@rikas - I've sent you an invite to the rubygems.org project (to your publicly listed github email address).

If anyone else from this thread is interested commit access, and to do some maintaining, here seems a good place to ask.

Anyway, time to crawl back into my hole.

Thanks all.

**Comment by reggieb** [comment]
I too haven't used geminabox for a few years. It makes a lot of sense if some of the current active users could take over maintenance. Happy to help out if people are stuck.

**Comment by rikas** [comment]
I've been around (still use geminabox) but I don't have much availability to be honest. Maybe @tnir could be a nice addition to maintainers? I love the work you've been doing :)

**Comment by kerrizor** [comment]
@tomlea happy to lend a hand, although my time is a bit limited

**Comment by deivid-rodriguez** [comment]
Also happy to lend a hand too, and also time limited :)

**Comment by tnir** [comment]
I just would say there is a lack of automation around review, approval, and release to `RubyGems.org` in this repo. Once I finish to automate such stuffs in a short time, we do not have time to take. I would be happy to be a maintainer in this GitHub as well as an owner of geminabox gem (`tnir`). @tomlea (or someone else) Can you add me to both?

**Comment by skaes** [comment]
@tomlea [we](https://www.xing.com) have been running a pair of geminabox servers (manual failover, rsync for async data replication) for over 10 years now and they never required a lot of attention. So thanks a lot for this project! Recent changes in bundler have made it necessary for us to have the compact index API. Another problem I'd like to tackle is gem deletion, which currently requires a full index rebuild and that takes 5 minutes during which the server is blocked for changes.

I can spend time on this project in the upcoming weeks/months and push/PR review rights would help. I have, for a while, maintained ruby-prof, but I'm not really active there anymore.

**Comment by tnir** [comment]
@tomlea Would you mind inviting me to @geminabox org instead of geminabox/geminabox? Also I would like to ask you add me to rubygem.org/gems/geminabox as well?

**Comment by rikas** [comment]
@tnir I added you to geminabox/geminabox, but I can't add you to @geminabox (I don't have permissions). But I can add you to rubygems I guess, and you can release new versions.

**Comment by tnir** [comment]
@rikas So, could you add me to RubyGems?

**Comment by tnir** [comment]
@rikas Now I got it 🙏 . At that time, I was just on mobile and could not see mailbox 😁 .

**Comment by tnir** [comment]
Closing as problems stated in the description were already resolved except for one. Thank you for your cooperation 😍
