### ISSUE TITLE
Add Org Owner permission to active maintainers

### ISSUE THREAD

**Issue by tnir** [geminabox/geminabox#395]
@tomlea Would you mind inviting me to @geminabox org instead of geminabox/geminabox? Also I would like to ask you add me to rubygem.org/gems/geminabox as well?

### Resources

https://docs.github.com/en/organizations/managing-peoples-access-to-your-organization-with-roles/maintaining-ownership-continuity-for-your-organization

> # Maintaining ownership continuity for your organization
Organizations can have more than one organization owner to avoid lapses in ownership.

> Organization owners can promote any member of an organization to an organization owner.

_Originally posted by @tnir in https://github.com/geminabox/geminabox/issues/381#issuecomment-1157029951_

**Comment by tnir** [comment]
@reggieb Thought?

**Comment by tomlea** [comment]
Done. Not sure why I didn't do that in the first place.

**Comment by reggieb** [comment]
Sounds good to me.

**Comment by tnir** [comment]
Thank you! @tomlea @reggieb 💞

**Comment by tnir** [comment]
Found only @tomlea and @pipt Org owners, and others are still Org members...

**Comment by tnir** [comment]
@pipt @tomlea Could you add me as Org Owner, not Org Member?
