### ISSUE TITLE
Improve bundled Dockerfile

### ISSUE THREAD

**Issue by tnir** [geminabox/geminabox#473]
While #305 updated the original Dockerfile introduced in #201, we can improve it.

**Comment by mohitsaxenaknoldus** [comment]
Hey, can I work on this?

**Comment by tnir** [comment]
@mohitsaxenaknoldus Yes, please.

**Comment by tnir** [comment]
@mohitsaxenaknoldus Can you create a PR? If not possible in 7 days, I would remove you from assignees to accept contributions widely.

**Comment by mohitsaxenaknoldus** [comment]
@tnir Sorry for being late, here's the PR: https://github.com/geminabox/geminabox/pull/487
