### ISSUE TITLE
Non-Compliance with Dependency API Deprecation

### ISSUE THREAD

**Issue by LukeIGS** [geminabox/geminabox#536]
https://blog.rubygems.org/2023/02/22/dependency-api-deprecation.html

From this document:
March 22 at 00:00 UTC (4pm PT / 7pm ET) for 5 minutes
March 29 at the top of every hour UTC for 10 minutes
April 03 for the entire day UTC
April 10 from 00:00 UTC onward

As of April 10th the dependency API on rubygems.org will be deprecated.  They're running a test brownout today on the third.  Attempting to pull gems via the rubygems proxy will return a 404 error, like this one.
https://gist.github.com/LukeIGS/d28433f789bcba619e1b50885adb38f9

**Comment by Eusebius1920** [comment]
Is there any way fixing this? A workaround?

May 10th is approaching...

**Comment by natebird** [comment]
This PR uses the modern ruby gems API - https://github.com/geminabox/geminabox/pull/435

**Comment by Eusebius1920** [comment]
Any news on this or #435 ?

**Comment by LukeIGS** [comment]
The issue with that solution is that it's wildly slow, the real solution here is to get that PR listed above merged.

**Comment by marvinthepa** [comment]
That is why I wrote "workaround", "quick-and-dirty fix", and not "solution".

Of course merging the pull request would be better, but that is outside of my power. So I thought others might be interested in a workaround as well.

**Comment by vshunkov** [comment]
Not sure if [#435](https://github.com/geminabox/geminabox/pull/435) resolves the issue of API dependency deprecation. I have built an image based on it, but I am still encountering the same problem as with the master branch. Has anyone else attempted to test it as well?

**Comment by LukeIGS** [comment]
Still in dev

**Comment by marvinthepa** [comment]
@github-actions You are starting to sound like a broken record.

Btw. if somebody is searching for another workaround (using different software): [Nexus OSS](https://www.sonatype.com/products/sonatype-nexus-oss-download) seems to have fixed the issue, and supports many more package formats besides rubygems.

**Comment by LukeIGS** [comment]
ping.

**Comment by LukeIGS** [comment]
Sneaky github actions bot closing this while i was out for holiday.
Could a contributor reopen this?
