### ISSUE TITLE
Can't add to sources until someone uploads a gem

### ISSUE THREAD

**Issue by jheiss** [geminabox/geminabox#65]
If you fire up a fresh geminabox server and then attempt to add it to your gem sources it fails:

jheiss@sleet:~/junk> gem sources -a http://localhost:8080/
Error fetching http://localhost:8080/:
	bad response Not Found 404 (http://localhost:8080/specs.4.8.gz)

As soon as you upload a gem it starts working.

**Comment by Mani082** [comment]
Same issue I faced. But when I carefully looked at the output, I found this, which resolved the issue.

```
ERROR:  Your gem push credentials file located at:

        /root/.gem/credentials

has file permissions of 0644 but 0600 is required.

To fix this error run:

        chmod 0600 /root/.gem/credentials
```
