### ISSUE TITLE
No gems shown in the index

### ISSUE THREAD

**Issue by mfloryan** [geminabox/geminabox#84]
ruby-1.9.1
geminabox 0.8.0
Windows Server 2008 R2 SP1 (64bit)

After installing the geminabox server it is starting OK, presents an index page but every time a new gem is uploaded (either through the upload button or through gem inabox command) the indexing seems to fail with the following error:

ERROR:  Unable to process ./data/gems/bundler-1.2.2.gem
no metadata found in ./data/gems/bundler-1.2.2.gem (Gem::Package::FormatError)

The same happens for any gem I tried. The index page does not list any installed gems (from the spec I suspect it should). However, gem install does seem to work for some of the gems.

**Comment by kmai00** [comment]
I know this is closed and over, but I recently bumped into this problem with 0.,12.4.

The problem for me is that in the config.ru, i was having the data dir set as "E:\\data" instead of "E:/data"
